language: ruby
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
  - jruby-head
  - rbx-3.107

install: gem install net-ssh test-unit mocha

script: rake test

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-3.107
